In [2]:
import pandas as pd
import json
from pandas.io.json import json_normalize

In [22]:
json = pd.read_json('C:/Users/Owner/Documents/data_science/1574117884_data_wrangling_json_5_/data_wrangling_json/data/world_bank_projects.json')
json.head(2)

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{'$oid': '52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{'Percent': 100, 'Name': 'Education for all'}","[{'code': '65', 'name': 'Education for all'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{'$oid': '52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{'Percent': 30, 'Name': 'Other economic manage...","[{'code': '24', 'name': 'Other economic manage...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en

In [10]:
#Import of json file with json.load
import json

with open('C:/Users/Owner/Documents/data_science/1574117884_data_wrangling_json_5_/data_wrangling_json/data/World_Bank_projects_less.json') as f:
    data = json.load(f)

In [11]:
#Normalized table of json data using json_normalize

import pandas as pd 
import json
from pandas.io.json import json_normalize

data= json.load((open('C:/Users/Owner/Documents/data_science/1574117884_data_wrangling_json_5_/data_wrangling_json/data/World_Bank_projects.json')))
normalized_data = json_normalize(data)

In [17]:
#10 top countries with highest submission of projects

df = pd.read_json('C:/Users/Owner/Documents/data_science/1574117884_data_wrangling_json_5_/data_wrangling_json/data/world_bank_projects.json')
df_top_freq = df['country_namecode'].value_counts()
print(df_top_freq.head(10))

Republic of Indonesia!$!ID              19
People's Republic of China!$!CN         19
Socialist Republic of Vietnam!$!VN      17
Republic of India!$!IN                  16
Republic of Yemen!$!RY                  13
People's Republic of Bangladesh!$!BD    12
Kingdom of Morocco!$!MA                 12
Nepal!$!NP                              12
Africa!$!3A                             11
Republic of Mozambique!$!MZ             11
Name: country_namecode, dtype: int64

In [24]:
#10 top project names/sectors

import pandas as pd
import json
from pandas.io.json import json_normalize

data= json.load((open('C:/Users/Owner/Documents/data_science/1574117884_data_wrangling_json_5_/data_wrangling_json/data/World_Bank_projects.json')))
normalized_data = json_normalize(data, record_path='mjtheme_namecode')
df = pd.DataFrame(normalized_data)
df_sorted = df['name'].value_counts()
print(df_sorted.head(10))

Environment and natural resources management    223
Rural development                               202
Human development                               197
Public sector governance                        184
Social protection and risk management           158
Financial and private sector development        130
                                                122
Social dev/gender/inclusion                     119
Trade and integration                            72
Urban development                                47
Name: name, dtype: int64

In [12]:
# All projects names that were missing have been filled using project codes

import numpy as np

data= json.load((open('C:/Users/Owner/Documents/data_science/1574117884_data_wrangling_json_5_/data_wrangling_json/data/World_Bank_projects.json')))
normalized_data = json_normalize(data, record_path='mjtheme_namecode')
df = pd.DataFrame(normalized_data)
new_df = (df.replace({'name':{'':np.nan}})
          .sort_values(['code', 'name'])
          .fillna(method='ffill')
          .sort_index())
print(new_df)

     code                                          name
0       8                             Human development
1      11  Environment and natural resources management
2       1                           Economic management
3       6         Social protection and risk management
4       5                         Trade and integration
5       2                      Public sector governance
6      11  Environment and natural resources management
7       6         Social protection and risk management
8       7                   Social dev/gender/inclusion
9       7                   Social dev/gender/inclusion
10      5                         Trade and integration
11      4      Financial and private sector development
12      6         Social protection and risk management
13      6         Social protection and risk management
14      2                      Public sector governance
15      4      Financial and private sector development
16     11  Environment and natural resources management
17      8                             Human development
18     10                             Rural development
19      7                   Social dev/gender/inclusion
20      2                      Public sector governance
21      2                      Public sector governance
22      2                      Public sector governance
23     10                             Rural development
24      2                      Public sector governance
25     10                             Rural development
26      6         Social protection and risk management
27      6         Social protection and risk management
28     11  Environment and natural resources management
29      4      Financial and private sector development
...   ...                                           ...
1469    8                             Human development
1470    9                             Urban development
1471    6         Social protection and risk management
1472    6         Social protection and risk management
1473    9                             Urban development
1474    2                      Public sector governance
1475    2                      Public sector governance
1476   10                             Rural development
1477   11  Environment and natural resources management
1478    8                             Human development
1479    7                   Social dev/gender/inclusion
1480   11  Environment and natural resources management
1481    5                         Trade and integration
1482    6         Social protection and risk management
1483    8                             Human development
1484    4      Financial and private sector development
1485    7                   Social dev/gender/inclusion
1486    8                             Human development
1487    5                         Trade and integration
1488    2                      Public sector governance
1489    8                             Human development
1490   10                             Rural development
1491    6         Social protection and risk management
1492   10                             Rural development
1493   10                             Rural development
1494   10                             Rural development
1495    9                             Urban development
1496    8                             Human development
1497    5                         Trade and integration
1498    4      Financial and private sector development

[1499 rows x 2 columns]